# Generated by Django 5.2.3 on 2025-08-09 02:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactarUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('email', models.EmailField(max_length=255, verbose_name='Correo Electronico')),
                ('telefono', models.BigIntegerField(verbose_name='Teléfono')),
                ('motivo', models.CharField(choices=[('General', 'General'), ('Citas', 'Citas'), ('Resultados', 'Resultados'), ('Manual de usuario', 'Manual')], max_length=20, verbose_name='Motivo')),
                ('mensaje', models.TextField(max_length=200, verbose_name='Mensaje')),
                ('contactar', models.CharField(choices=[('Teléfono', 'Telefono'), ('Correo Electrónico', 'Email')], max_length=20, verbose_name='Medio de contacto')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CrearHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de horario')),
                ('hora_inicio', models.TimeField(default='08:00', verbose_name='Hora de inicio')),
                ('hora_final', models.TimeField(default='18:00', verbose_name='Hora de final')),
                ('duracion', models.IntegerField(default=20, verbose_name='Duración de Cita')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora_cita', models.TimeField(verbose_name='Hora de inicio')),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('Agendada', 'Agendada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], default='Disponible', max_length=20, verbose_name='Estado cita')),
                ('asistencia', models.CharField(choices=[('Asistio', 'Asistio'), ('No asistio', 'No Asistio'), ('A la espera', 'Espera')], default='A la espera', max_length=20, verbose_name='Asistencia')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.crearhorario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.horariocita')),
            ],
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_consulta', models.TextField(max_length=500, verbose_name='Motivo de consulta')),
                ('diagnostico', models.TextField(max_length=500, verbose_name='Diagnóstico')),
                ('tratamiento', models.TextField(max_length=500, verbose_name='Tratamiento')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Consulta')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('id_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.usuariocitas', verbose_name='Cita asignada')),
            ],
        ),
        migrations.CreateModel(
            name='CreacionUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_id', models.CharField(choices=[('Cédula', 'Cedula'), ('Tarjeta Identidad', 'Tarjeta Id'), ('Cédula Extranjería', 'Ced Ext'), ('Pasaporte', 'Pasaporte')], default='Cédula', max_length=20, verbose_name='Tipo de documento')),
                ('numero_id', models.PositiveBigIntegerField(default=0, unique=True, verbose_name='Numero de identificación')),
                ('telefono', models.PositiveBigIntegerField(default=0, verbose_name='Teléfono')),
                ('tipo_usuario', models.CharField(choices=[('Administrador', 'Admin'), ('Paciente', 'Paciente'), ('Medico', 'Medico'), ('Recepcionista', 'Recepcion')], default='Paciente', max_length=20, verbose_name='Tipo Usuario')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualización')),
                ('nombre_completo', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('cambiar_contrasena', models.BooleanField(default=True, verbose_name='Cambiar contraseña')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='usuariocitas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.CreateModel(
            name='HabilitarDeshabilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='crearhorario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Medico'),
        ),
    ]
