# Generated by Django 5.2.3 on 2025-08-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocitas',
            name='actividad_cita',
            field=models.CharField(default='Asignada', max_length=20, verbose_name='Estado Cita'),
        ),
        migrations.AlterField(
            model_name='horariocita',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agendada', 'Agendada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], default='Disponible', max_length=20, verbose_name='Estado'),
        ),
    ]
