# Generated by Django 5.1.5 on 2025-07-11 04:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_alter_creacionuser_numero_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactarusuario',
            name='contactar',
            field=models.CharField(choices=[('Teléfono', 'Telefono'), ('Correo Electrónico', 'Email')], max_length=20, verbose_name='Medio de contacto'),
        ),
        migrations.AlterField(
            model_name='contactarusuario',
            name='motivo',
            field=models.CharField(choices=[('General', 'General'), ('Citas', 'Citas'), ('Resultados', 'Resultados'), ('Manual de usuario', 'Manual')], max_length=20, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='creacionuser',
            name='fecha_actualizacion',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ultima Actualización'),
        ),
        migrations.AlterField(
            model_name='creacionuser',
            name='numero_id',
            field=models.PositiveBigIntegerField(default=0, unique=True, verbose_name='Numero de identificación'),
        ),
        migrations.AlterField(
            model_name='creacionuser',
            name='telefono',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='creacionuser',
            name='tipo_id',
            field=models.CharField(choices=[('Cédula', 'Cedula'), ('Tarjeta Identidad', 'Tarjeta Id'), ('Cédula Extranjería', 'Ced Ext'), ('Pasaporte', 'Pasaporte')], default='Cédula', max_length=20, verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='creacionuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('Administrador', 'Admin'), ('Paciente', 'Paciente'), ('Medico', 'Medico'), ('Recepcionista', 'Recepcion')], default='Paciente', max_length=20, verbose_name='Tipo Usuario'),
        ),
    ]
