# Generated by Django 5.1.5 on 2025-07-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_alter_contactarusuario_contactar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creacionuser',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualización'),
        ),
    ]
