# Generated by Django 5.1.5 on 2025-07-15 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_alter_creacionuser_fecha_actualizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrearHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de horario')),
                ('hora_inicio', models.TimeField(default='08:00', verbose_name='Hora de inicio')),
                ('hora_final', models.TimeField(default='08:00', verbose_name='Hora de final')),
                ('duracion', models.IntegerField(default=20, verbose_name='Duracion de Cita')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HabitarDeshabilitar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de inicio')),
                ('hora_final', models.TimeField(verbose_name='Hora de final')),
                ('disponible', models.BooleanField(default=True)),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.crearhorario')),
            ],
        ),
    ]
