# Generated by Django 5.1.5 on 2025-07-16 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_alter_crearhorario_hora_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearhorario',
            name='tipo_usuario',
            field=models.CharField(default='Medico', max_length=30),
        ),
    ]
