# Generated by Django 5.1.5 on 2025-07-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_crearhorario_tipo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crearhorario',
            name='tipo_usuario',
        ),
    ]
