# Generated by Django 5.1.5 on 2025-07-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_remove_crearhorario_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='horariocita',
            old_name='hora_inicio',
            new_name='hora_cita',
        ),
        migrations.RemoveField(
            model_name='horariocita',
            name='hora_final',
        ),
        migrations.AddField(
            model_name='horariocita',
            name='fecha',
            field=models.DateField(default='2025-07-15', verbose_name='Fecha'),
            preserve_default=False,
        ),
    ]
