# Generated by Django 5.1.5 on 2025-07-19 22:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_rename_hora_inicio_horariocita_hora_cita_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crearhorario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
