# Generated by Django 5.1.5 on 2025-07-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_crearhorario_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionuser',
            name='nombre_completo',
            field=models.CharField(default='prueba', max_length=100, verbose_name='Nombre completo'),
            preserve_default=False,
        ),
    ]
