# Generated by Django 5.1.5 on 2025-07-21 21:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0011_creacionuser_nombre_completo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioCitas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.horariocita')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
