# Generated by Django 5.1.5 on 2025-07-22 02:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_usuariocitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocitas',
            name='fecha',
        ),
        migrations.AddField(
            model_name='usuariocitas',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
