# Generated by Django 5.1.5 on 2025-07-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_remove_usuariocitas_fecha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariocita',
            name='disponible',
        ),
        migrations.AddField(
            model_name='horariocita',
            name='estado',
            field=models.CharField(choices=[('Disponible', 'Disponible'), ('Agendada', 'Agendada'), ('Reprogramada', 'Reprogramada'), ('Cancelada', 'Cancelada')], default='Disponible', max_length=20, verbose_name='Estado cita'),
        ),
    ]
