# Generated by Django 5.1.5 on 2025-07-22 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0014_remove_horariocita_disponible_horariocita_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocitas',
            name='estado_cita',
            field=models.CharField(default='Agendada', max_length=20, verbose_name='Estado cita'),
            preserve_default=False,
        ),
    ]
