# Generated by Django 5.2.3 on 2025-07-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0016_crearhorario_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HabitarDeshabilitar',
            new_name='HabilitarDeshabilitar',
        ),
    ]
