# Generated by Django 5.2.3 on 2025-07-23 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0017_rename_habitardeshabilitar_habilitardeshabilitar'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitardeshabilitar',
            name='estado',
            field=models.CharField(default='Habilitando', max_length=20),
            preserve_default=False,
        ),
    ]
