# Generated by Django 5.2.3 on 2025-07-26 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0018_habilitardeshabilitar_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='creacionuser',
            name='cambiar_contrasena',
            field=models.BooleanField(default=True, verbose_name='Cambiar contraseña'),
        ),
        migrations.AddField(
            model_name='horariocita',
            name='asistencia',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Asistencia'),
        ),
    ]
